FROM node:lts-alpine3.11

WORKDIR /app

COPY ./.npmrc /app
COPY ./.eslintrc /app
COPY ./.babelrc /app
COPY ./package.json /app
COPY ./webpack.common.js /app
COPY ./webpack.dev.js /app
COPY ./package.json /app/package.json
COPY ./src /app/src

RUN npm install

EXPOSE 9000

CMD ["npm", "start"]